model:
  model_type: random_forest
  model_version: 2.1.0
  random_state: 42
  test_size: 0.2
  validation_size: 0.2
  stratify: true
  invert_target: false
  use_smote: false
  smote_random_state: 42
  smote_target_ratio: 0.3
  smote_k_neighbors: 2
  cv_folds: 5
  cv_random_state: 42
  primary_metric: average_precision
  metrics:
  - accuracy
  - precision
  - recall
  - f1
  - roc_auc
  - pr_auc
  - average_precision
  model_specific_smote:
    gradient_boosting: false
    xgboost: false
    random_forest: false
    logistic_regression: false
    svm: false
    naive_bayes: false
features:
  data_leakage_features:
  - PHYS_TREAT_RATE_ALL
  - PATIENT_ID
  - PHYSICIAN_ID
  - DISEASEX_DT
  - SYMPTOM_ONSET_DT
  temporal_leakage_features: []
  production_features:
  - PATIENT_AGE
  - PATIENT_GENDER
  - RISK_IMMUNO
  - RISK_CVD
  - RISK_DIABETES
  - RISK_OBESITY
  - RISK_NUM
  - RISK_AGE_FLAG
  - PHYS_EXPERIENCE_LEVEL
  - PHYSICIAN_STATE
  - PHYSICIAN_TYPE
  - PHYS_TOTAL_DX
  - SYM_COUNT_5D
  - LOCATION_TYPE
  - INSURANCE_TYPE_AT_DX
  - SYMPTOM_TO_DIAGNOSIS_DAYS
  - DIAGNOSIS_WITHIN_5DAYS_FLAG
  - SYMPTOM_ACUTE_PHARYNGITIS
  - SYMPTOM_ACUTE_URI
  - SYMPTOM_CHILLS
  - SYMPTOM_CONGESTION
  - SYMPTOM_COUGH
  - SYMPTOM_DIARRHEA
  - SYMPTOM_DIFFICULTY_BREATHING
  - SYMPTOM_FATIGUE
  - SYMPTOM_FEVER
  - SYMPTOM_HEADACHE
  - SYMPTOM_LOSS_OF_TASTE_OR_SMELL
  - SYMPTOM_MUSCLE_ACHE
  - SYMPTOM_NAUSEA_AND_VOMITING
  - SYMPTOM_SORE_THROAT
  - PRIOR_CONTRA_LVL
  - DX_SEASON
  categorical_features:
  - PATIENT_GENDER
  - PHYS_EXPERIENCE_LEVEL
  - PHYSICIAN_STATE
  - PHYSICIAN_TYPE
  - LOCATION_TYPE
  - INSURANCE_TYPE_AT_DX
  - DX_SEASON
  target_column: TARGET
paths:
  raw_data_dir: data/raw
  processed_data_dir: data/processed
  model_ready_data_dir: data/model_ready
  model_dir: backend/ml_models
  feature_dictionary_path: data/model_ready/model_feature_dictionary.xlsx
  model_ready_dataset_path: data/model_ready/model_ready_dataset.csv
  reports_dir: reports
  logs_dir: logs
hyperparameters:
  xgboost: &id001
    n_estimators: 799
    learning_rate: 0.2610570842357371
    max_depth: 7
    subsample: 0.9130034518395074
    colsample_bytree: 0.8549084927445061
    reg_alpha: 0.3040562063700757
    reg_lambda: 1.9851311518315806
    min_child_weight: 3
    gamma: 0.029685899839029244
    random_state: 42
    n_jobs: -1
    eval_metric: logloss
    early_stopping_rounds: 20
  random_forest:
    n_estimators: 50
    max_depth: 6
    min_samples_split: 30
    min_samples_leaf: 15
    class_weight: balanced
    random_state: 42
    n_jobs: -1
    max_features: sqrt
  logistic_regression:
    C: 0.1
    penalty: l2
    solver: liblinear
    class_weight: balanced
    random_state: 42
    max_iter: 2000
    fit_intercept: true
  gradient_boosting:
    max_iter: 100
    learning_rate: 0.05
    max_depth: 6
    class_weight: balanced
    random_state: 42
    max_leaf_nodes: 31
    early_stopping: false
  naive_bayes:
    var_smoothing: 1.0e-09
  svm:
    C: 0.1
    kernel: rbf
    gamma: scale
    class_weight: balanced
    random_state: 42
    probability: true
environments:
  development:
    cv_folds: 3
    hyperparameters:
      xgboost: *id001  # Use same optimized parameters as production
      random_forest:
        n_estimators: 50
      gradient_boosting:
        max_iter: 80
      logistic_regression:
        max_iter: 1000
  testing:
    cv_folds: 3
    test_size: 0.3
    hyperparameters:
      xgboost: *id001  # Use same optimized parameters as production
      random_forest:
        n_estimators: 25
      gradient_boosting:
        max_iter: 50
  staging:
    cv_folds: 5
    hyperparameters:
      xgboost: *id001  # Use same optimized parameters as production
      random_forest:
        n_estimators: 100
      gradient_boosting:
        max_iter: 150
  production:
    cv_folds: 5
    hyperparameters:
      xgboost: *id001
      random_forest:
        n_estimators: 100
        min_samples_split: 25
        min_samples_leaf: 12
      gradient_boosting:
        max_iter: 150
      logistic_regression:
        max_iter: 2500
    model_type: xgboost
